version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      MYSQL_DATABASE: app_db
      MYSQL_DRIVER: mysql
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    image: mysql:8
    restart: always
    ports:
      - "3366:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    volumes:
      - ./db_data:/var/lib/mysql
    healthcheck:
          test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
          interval: 2s
          timeout: 15s
          retries: 10

volumes:
  mysql_db: