version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    environment:
      PGSQL_USER: db_user
      PGSQL_PASSWORD: db_user_pass213
      PGSQL_DATABASE: app_db
      PGSQL_DRIVER: postgres
    depends_on:
      - database
    networks:
      - myapp

  database:
    image: postgres:16.0-alpine3.18
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_user_pass213
    networks:
      - myapp
    ports:
      - "5432:5432"
    volumes:
      - ./internal/infrastructure/migrations/postgresql/0001_inital.up.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  myapp:
    driver: bridge
