CREATE TABLE IF NOT EXISTS languages
(
    id   integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255) NOT NULL
);

INSERT INTO languages (id, name)
VALUES (1, 'Pascal'),
       (2, 'C'),
       (3, 'C++'),
       (4, 'JavaScript'),
       (5, 'PHP'),
       (6, 'Python'),
       (7, 'Java'),
       (8, 'Haskel'),
       (9, 'Clojure'),
       (10, 'Prolog'),
       (11, 'Scala');


CREATE TABLE IF NOT EXISTS forms
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    fio       varchar(150) NOT NULL,
    phone     varchar(12)  NOT NULL,
    email     varchar(150) NOT NULL,
    birthday  date       NOT NULL,
    gender    varchar(1)   NOT NULL,
    biography text
);

CREATE TABLE IF NOT EXISTS forms_languages
(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_form int NOT NULL,
    id_lang int NOT NULL
);